Fix CI when testing with Symfony 5.1
doctrine/DoctrineBundle pull request #1160
Opened 2020-04-29 17:55 UTC by nicolas-grekas

2020-04-29 18:39 UTC, ostrolucky commented
Can you provide some backstory please? Why are we not asserting now that tags contain `container.no_preload` *only*, but instead trying to hiding this fact?

2020-04-29 18:48 UTC, nicolas-grekas commented
`container.no_preload` is added because the only services that reference the tested listener are commands, and commands propagate this tag to their deps.
Testing this is unrelated to the bundle, so it should just be ignored here.

2020-04-29 19:01 UTC, greg0ire commented
The CI still fails, I will push a commit that fixes it shortly.

2020-04-29 19:11 UTC, nicolas-grekas commented
The fix for deprecations should be borrowed from master

2020-04-29 19:13 UTC, greg0ire commented
Oh didn't know, I'll fix this.

2020-04-29 19:16 UTC, greg0ire approved these changes

2020-04-29 20:34 UTC, SenseException approved these changes

2020-05-04 12:08 UTC, ostrolucky commented
You ask for my approval, but I am still uncomfortable with this unset thing. We should change assertions to use `$definition->getTags()['doctrine.event_subscriber']` / `$definition->getTags()['doctrine.event_listener']`, instead of coupling these test cases more tightly to Symfony DI by hardcoding their internal tags. In the end these asertions were wrong. These test cases shouldn't care about other tags, just tags we are touching - and adding every other tag in future to unset() later on just doesn't scale.

2020-05-04 12:13 UTC, nicolas-grekas commented
@ostrolucky thanks for the suggestion, I updated the PR accordingly. I hope it's OK for everyone else also.

2020-05-04 12:18 UTC, ostrolucky approved these changes

2020-05-04 12:21 UTC, ostrolucky requested changes

2020-05-04 12:21 UTC, ostrolucky commented on Tests/DependencyInjection/AbstractDoctrineExtensionTest.php
> +        $this->assertSame([ ['event' => 'loadClassMetadata'] ], $definition->getTags()['doctrine.event_subscriber']);
```suggestion
        $this->assertSame([ ['event' => 'loadClassMetadata'] ], $definition->getTags()['doctrine.event_listener']);
```

2020-05-04 12:30 UTC, ostrolucky approved these changes
Thanks for bearing with me!

2020-05-04 12:33 UTC, merged