add RegisterUidTypePass
doctrine/DoctrineBundle pull request #1207
Opened 2020-09-04 07:16 UTC by gennadigennadigennadi

As a result from https://github.com/symfony/symfony/pull/37678, this PR is the last missing piece to implement symfony/uid as DoctrineTypes.

2020-09-04 07:25 UTC, ostrolucky requested changes
This won't work with Symfony 4.4 that we need to support.

2020-09-04 07:55 UTC, gennadigennadigennadi commented
What about adding a check if the Pass is available then only add it if it is so?

2020-09-04 08:04 UTC, ostrolucky commented
Well of course. After that, you also need to revert composer.json changes

2020-09-07 20:08 UTC, greg0ire approved these changes

2020-09-07 21:17 UTC, merged

2020-11-13 14:49 UTC, DavidBadura commented
I am wondering if the automatic type registration can also be deactivated / prevented.

The background is that we use the Ramsey UUID Lib in many projects and want to stay with it. The doctrine type "uuid" is already defined by Ramsey Doctrine Extension. So you should have a conflict here, right?