Add config parameter for read-only SQLite databases
doctrine/DoctrineBundle pull request #1213
Opened 2020-09-23 21:07 UTC by Ma27

See https://github.com/doctrine/dbal/pull/4292

2020-09-23 22:24 UTC, ostrolucky requested changes
Requires documentation, xsd updates

2020-09-23 22:24 UTC, ostrolucky commented on DependencyInjection/Configuration.php
> +                ->booleanNode('read_only')->end()
should define info explaining this, similarly as is done for `persistent` option

2020-09-24 12:48 UTC, Ma27 commented
@ostrolucky thanks, fixed :)

The build failure appears unrelated as it's also broken on `master`.

2020-09-27 20:30 UTC, Ma27 commented
Just pushed an update: the DBAL maintainers preferred to not have this kind of logic in their library however I think that it's still useful to have this setting accessible and exposed in a config layer like this bundle. For further references to the original discussion, please take a look at the commit message :)

2020-09-27 21:12 UTC, ostrolucky commented
Sorry, I agree with @morozov. This adds just yet another abstraction level to real driver option that doesn't work for any other drivers. Rather confusing if users can just use existing constant for a driver option for same thing. Also, we generally do not add driver options here that do not exist in DBAL, I would recommend to wait until feature is accepted in DBAL first before working on its integration here. Thanks for proposing though!

2020-09-27 21:12 UTC, closed without merging