[Waiting code merge] Register remember me schema subscriber from Symfony Bridge
doctrine/DoctrineBundle pull request #1297
Opened 2021-02-25 11:08 UTC by wouterj

This PR register the `RememberMeTokenProviderDoctrineSchemaSubscriber` schema listener that will be introduced in #40145 . This way, Doctrine's schema system can help the user create and update their remember me table.

2021-02-25 11:12 UTC, stof requested changes
This service definition should be conditional, to keep support for Symfony versions not having it (the bundle supports the 4.4 LTS too)

2021-02-25 11:30 UTC, wouterj commented
Thanks for the quick review @stof! The definition is optional now.

2021-02-25 19:40 UTC, SenseException approved these changes

2021-04-11 15:37 UTC, wouterj commented
The related Symfony PR has been merged and it will be part of the upcoming 5.3 release. So I think this PR is ready to be merged.

2021-04-16 15:56 UTC, ostrolucky approved these changes

2021-04-16 15:57 UTC, merged