Deprecate `override_url` configuration option
doctrine/DoctrineBundle pull request #1342
Opened 2021-05-10 15:41 UTC by nicolas-grekas

Extracted from #1335

2021-05-10 16:05 UTC, stof requested changes

2021-05-10 16:05 UTC, stof commented on DependencyInjection/Configuration.php
> +                    @trigger_error(sprintf('The "doctrine.dbal.%s" %s deprecated since DoctrineBundle 2.4, use the "doctrine.dbal.url" option instead.', implode('", "doctrine.dbal.', array_keys($depr
why not using `setDeprecated()` on the boolean node instead ?

2021-05-10 16:18 UTC, nicolas-grekas commented on DependencyInjection/Configuration.php
> +                    @trigger_error(sprintf('The "doctrine.dbal.%s" %s deprecated since DoctrineBundle 2.4, use the "doctrine.dbal.url" option instead.', implode('", "doctrine.dbal.', array_keys($depr
To reduce the diff with # #1335, since there, we'll want to group deprecations in one.

2021-05-13 08:10 UTC, ostrolucky requested changes
Can you please rebase, there were some cs changes and merging this PR would make target branch failing

2021-05-13 08:10 UTC, ostrolucky commented on ConnectionFactory.php
> +            $overriddenOptions = [];
Why else? Make it default instead

2021-05-13 08:15 UTC, nicolas-grekas commented on ConnectionFactory.php
> +            $overriddenOptions = [];
updated

2021-05-13 08:17 UTC, ostrolucky approved these changes

2021-05-13 08:21 UTC, merged