Fix db name suffix parsing for replica
doctrine/DoctrineBundle pull request #1470
Opened 2022-02-08 10:11 UTC by kschusternetformic

2022-02-13 09:21 UTC, ostrolucky commented
test required

2022-02-13 09:23 UTC, ostrolucky requested changes

2022-02-13 09:23 UTC, ostrolucky commented on ConnectionFactory.php
> +            if (isset($params['replica']) && isset($params['replica']['dbname']) && isset($params['replica']['dbname_suffix'])) {
```suggestion
            if (isset($params['replica']['dbname'], $params['replica']['dbname_suffix'])) {
```

2022-02-13 09:23 UTC, ostrolucky commented on ConnectionFactory.php
> +            if (isset($params['primary']) && isset($params['primary']['dbname']) && isset($params['primary']['dbname_suffix'])) {
```suggestion
            if (isset($params['primary']['dbname'], $params['primary']['dbname_suffix'])) {
```

2022-02-24 12:46 UTC, kschusternetformic commented
@ostrolucky Tests were added

2022-02-26 19:21 UTC, merged