Use a modern directory structure
doctrine/DoctrineBundle pull request #1767
Opened 2024-03-14 22:13 UTC by greg0ire

The recommended directory structure is more similar to what we do in non-bundle repositories.
Also, this means smaller configuration for tools such as PHPCSStandards, PHPUnit or Psalm.

2024-03-14 22:18 UTC, greg0ire commented
The Psalm failures demonstrate another reason why this is better: the `Middleware` directory was forgotten in this list:
https://github.com/doctrine/DoctrineBundle/blob/7150c1de28bcb3b73c1dc1017eda37582228dc85/psalm.xml.dist#L23-L33

2024-03-14 22:26 UTC, ostrolucky commented
yes, this is welcome

2024-03-14 22:31 UTC, greg0ire commented
I'm unsure where the 2 svg files should go. Should they go into `public`, or should I keep them under `templates/Collector`? They are referenced in https://github.com/doctrine/DoctrineBundle/blob/7150c1de28bcb3b73c1dc1017eda37582228dc85/Resources/views/Collector/db.html.twig#L11-L15

2024-03-14 23:13 UTC, ostrolucky commented
Keep them in templates. And let's target next minor.

2024-03-15 06:47 UTC, greg0ire commented
Will address the conflicts once #1768 is merged and merged up.

2024-03-15 14:00 UTC, stof requested changes
To support the modern structure, the DoctrineBundle class needs to be updated to override the `getPath()` method (or to extend AsbtractBundle which already does the override) as the bundle class is not at the root path of the bundle anymore.

2024-03-15 14:00 UTC, stof commented on composer.json
> +            "": "tests/DependencyInjection",
As this seems to be about autoloading the `Fixtures` namespace, I would suggest using `Fixtures\\` as the PSR-4 prefix (and going one level deeper for the path) instead of a fallback for any class.

2024-03-15 14:47 UTC, greg0ire commented on composer.json
> +            "": "tests/DependencyInjection",
👍 will do in a separate PR

2024-03-15 14:51 UTC, ostrolucky approved these changes

2024-03-15 14:51 UTC, merged

2024-03-15 14:54 UTC, greg0ire commented
> To support the modern structure, the DoctrineBundle class needs to be updated to override the getPath() method (or to extend AsbtractBundle which already does the override) as the bundle class is not at the root path of the bundle anymore.

@ostrolucky why did you merge? Is that not an issue?

2024-03-15 15:00 UTC, greg0ire commented
Addressed in https://github.com/doctrine/DoctrineBundle/pull/1770