Add support for validator automapping
doctrine/DoctrineBundle pull request #939
Opened 2019-03-31 19:07 UTC by dunglas

Add support for symfony/symfony#27735 in the bundle.

Related config:

```yaml
framework:
    validation:
        auto_mapping:
            App\\Entity\\: [doctrine.orm.default_entity_manager.validator_loader]
```

2019-03-31 19:54 UTC, greg0ire commented on DependencyInjection/DoctrineExtension.php
> +    private function loadValidatorLoader($entityManagerName, ContainerBuilder $container)
This package requires php 7.1, I think you can use type hints here:

```suggestion
    private function loadValidatorLoader(string: $entityManagerName, ContainerBuilder $container): void
```

2019-03-31 21:42 UTC, dunglas commented
I tested this PR on a real project, and it's working properly.

2019-03-31 22:17 UTC, Majkl578 commented
> and it's working properly

This will need some sort of test otherwise it can break in future. :|

2019-03-31 22:18 UTC, dunglas commented
Yes I totally agree. At least a functional test is mandatory.

2019-04-01 06:49 UTC, greg0ire approved these changes

2019-04-02 19:49 UTC, SenseException approved these changes

2019-04-02 19:51 UTC, SenseException requested changes
A phpcs issue is still there. Otherwise this is :+1:

2019-04-03 20:26 UTC, greg0ire commented on DependencyInjection/DoctrineExtension.php
> +        if (!class_exists(DoctrineLoader::class)) {
This should fix the build:
```suggestion
        if (! class_exists(DoctrineLoader::class)) {
```

2019-04-04 11:04 UTC, stof requested changes

2019-04-04 11:04 UTC, stof commented on DependencyInjection/DoctrineExtension.php
> +        if (! class_exists(DoctrineLoader::class)) {
This requires testing for LoaderInterface first as the bridge does not prevent installing its latest version without the Validator component (which is expected) and then that would be a fatal error due to the missing interface.

2019-04-04 19:31 UTC, SenseException approved these changes

2019-04-06 11:41 UTC, stof approved these changes

2019-04-06 12:27 UTC, merged

2019-04-06 12:59 UTC, dunglas commented
Thanks a lot for finishing this one Andreas!

2021-06-15 11:42 UTC, tarjei commented
It seems that the blogpost for this feature has not been updated with the info about auto enabling it:
https://symfony.com/blog/new-in-symfony-4-3-automatic-validation